// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNzcT2BD4t8WEViJc7Gt6sYxCAIvXm7ek',
    appId: '1:968089048982:web:26bf0784df0cc2033c2fb7',
    messagingSenderId: '968089048982',
    projectId: 'notes-app-88290',
    authDomain: 'notes-app-88290.firebaseapp.com',
    storageBucket: 'notes-app-88290.appspot.com',
    measurementId: 'G-MF2VN95P47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7EC_5exBJXqWaFoh9Dt_WWriYeUHDjm8',
    appId: '1:968089048982:android:ac8d516dee659ae43c2fb7',
    messagingSenderId: '968089048982',
    projectId: 'notes-app-88290',
    storageBucket: 'notes-app-88290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBmeoCLroTlUH-MPDise-HWo1hwX_A5FA',
    appId: '1:968089048982:ios:1ec89368ac7d6bdb3c2fb7',
    messagingSenderId: '968089048982',
    projectId: 'notes-app-88290',
    storageBucket: 'notes-app-88290.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBmeoCLroTlUH-MPDise-HWo1hwX_A5FA',
    appId: '1:968089048982:ios:1ec89368ac7d6bdb3c2fb7',
    messagingSenderId: '968089048982',
    projectId: 'notes-app-88290',
    storageBucket: 'notes-app-88290.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNzcT2BD4t8WEViJc7Gt6sYxCAIvXm7ek',
    appId: '1:968089048982:web:c31e188c5d1881f13c2fb7',
    messagingSenderId: '968089048982',
    projectId: 'notes-app-88290',
    authDomain: 'notes-app-88290.firebaseapp.com',
    storageBucket: 'notes-app-88290.appspot.com',
    measurementId: 'G-BGM36343GC',
  );
}
